name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Release-solution-PowerPlatform_Pipeline_Deployment:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: PowerPlatform_Pipeline_Deployment
      #Update your values here
      BUILD_ENVIRONMENT_URL: ${{vars.BUILD_ENVIRONMENT_URL}}
      PRODUCTION_ENVIRONMENT_URL: ${{vars.PROD_ENVIRONMENT_URL}}
      CLIENT_ID: ${{vars.CLIENT_ID}}
      TENANT_ID: ${{vars.TENANT_ID}}      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
